### ISSUE TITLE
Not working in latest SD forge

### ISSUE THREAD

**Issue by bboyles303** [rifeWithKaiju/model_preset_manager#18]
Been trying to get this working in forge, but seems to fail: 

*** Error executing callback ui_tabs_callback for /home/user/stable-diffusion-webui-forge/extensions/model_preset_manager/scripts/main.py
    Traceback (most recent call last):
      File "/home/user/stable-diffusion-webui-forge/modules/script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "/home/user/stable-diffusion-webui-forge/extensions/model_preset_manager/scripts/main.py", line 463, in on_ui_tabs
        model_generation_data = gr.Textbox(label = model_generation_data_label_text(), value = "", lines = 3, elem_id = "def_model_gen_data_textbox").style(show_copy_button=True)
    AttributeError: 'Textbox' object has no attribute 'style'

**Comment by OdinVex** [comment]
This is because the latest Gradio (v4+) deprecated and removed the `styles` this way. Even removing `.style(show_copy_button=True)` and restarting won't help because something else has changed.

Edit: You can remove all of those `styles` and it'll show up in the UI, you can even tinker in it. Edit: Just be sure to rename or move the .git folder so it won't reset your changes every start.

**Comment by Nubbie** [comment]
**Removed** `.style(show_copy_button=True)` and `.style(container=True, item_container=True)` and `.style(show_copy_button=True)` 
**in the file** `model_preset_manager\scripts\main.py`

The button came back but doesn't work, new errors occured

------------

<details><summary>Error message start-up:</summary>
<p>

```
C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\extensions\model_preset_manager\scripts\main.py:466: GradioDeprecationWarning: unexpected argument for CheckboxGroup: multiselect
  triggerWords = gr.CheckboxGroup([], multiselect=True, label="Trigger Words", interactive = True)
C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\extensions\model_preset_manager\scripts\main.py:507: GradioDeprecationWarning: unexpected argument for HTML: height
  model_url_output = gr.HTML(label="model page", height=800)
```

</p>
</details> 


<details><summary>Error message when pressing "Retrieve local model info"</summary>
<p>

```
Traceback (most recent call last):
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\extensions\model_preset_manager\scripts\main.py", line 265, in retrieve_model_info_from_disk
    short_hash, model_info = get_model_hash_and_info_from_model_filename(model_filename, False)
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\extensions\model_preset_manager\scripts\main.py", line 50, in get_model_hash_and_info_from_model_filename
    short_hash = get_short_hash_from_filename(model_filename)
  File "C:\AI\Stable diffusion Forge\Stable Diffusion Forge\webui\extensions\model_preset_manager\scripts\main.py", line 95, in get_short_hash_from_filename
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'NovaFurryXL.safetensors'
```

</p>
</details> 

-----------------

They layout also seem messed up

<img width="383" height="183" alt="Image" src="https://github.com/user-attachments/assets/b97aaaa4-30d7-4f5e-ae7d-855f938349e3" />

**version:** Stable diffusion forge [f2.0.1v1.10.1-previous-669-gdfdcbab6](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/dfdcbab685e57677014f05a3309b48cc87383167)
**python:** 3.10.9
**torch:** 2.7.0+cu128
**xformers:** N/A
**gradio:** 4.40.0

**Comment by OdinVex** [comment]
> show_copy_button

Unfortunately I'm stuck with Pascal-architecture GPUs and I'm forced to stick to a specific older version of Forge, so I can't assist. Edit: The errors seem to suggest an entire rewrite of the layout may be necessary and some updating for fetching the model path to the backend too.

**Comment by Nubbie** [comment]
If there is something I can do to help - I gladly will
I don't have any expectations as it's totally fair and reasonable considering the effort needed for this issue 


> Edit: The errors seem to suggest an entire rewrite of the layout

Snooped around in other extensions that did work and noticed some, like [stable-diffusion-webui-state](https://github.com/ilian6806/stable-diffusion-webui-state), have code that seem to [check and fallback depending on the version running](https://github.com/ilian6806/stable-diffusion-webui-state/blob/d59fe769f5754f0a091677070a62464f37249a08/javascript/state.core.js#L229-L248)
Seem like stuff work differently depending on which Gradio is running, mine is 4.40.0, not sure which is the most common one

**Comment by OdinVex** [comment]
> If there is something I can do to help - I gladly will I don't have any expectations as it's totally fair and reasonable considering the effort needed for this issue
> 
> > Edit: The errors seem to suggest an entire rewrite of the layout
> 
> Snooped around in other extensions that did work and noticed some, like [stable-diffusion-webui-state](https://github.com/ilian6806/stable-diffusion-webui-state), have code that seem to [check and fallback depending on the version running](https://github.com/ilian6806/stable-diffusion-webui-state/blob/d59fe769f5754f0a091677070a62464f37249a08/javascript/state.core.js#L229-L248) Seem like stuff work differently depending on which Gradio is running, mine is 4.40.0, not sure which is the most common one

Gradio 4 changed a lot about how UI stuff is done. Author would need to rewrite to support it.
