### ISSUE TITLE
error: ValueError: unknown file extension: no image in np array

### ISSUE THREAD

**Issue by SkyKn1ght** [rifeWithKaiju/model_preset_manager#2]
every times, when i drop any  image file into it,  nothing happened, but following error info in console:

The above exception was the direct cause of the following exception:

------
Traceback (most recent call last):
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\aigc\sd-webui\stable-diffusion-webui\extensions\model_preset_manager\scripts\main.py", line 177, in save_thumbnail_from_np_array
    image.save(thumbnail_path)
  File "f:\aigc\sd-webui\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2411, in save
    raise ValueError(msg) from e
ValueError: unknown file extension:
no image in np array
------

so, what's happened ?

**Comment by rifeWithKaiju** [comment]
looking into it.  what was the file extension, btw?

Edit: if you don't mind, could you share the image here?  I'm not able to reproduce this, and I tried a few images including non-standard ones like gif.
